import Provider from "@/utils/provider";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className="container p-4 flex flex-col justify-center items-center">
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
